Vagrant.configure("2") do |config|
  
  config.vm.provision "shell", path: "docker_provisioning.sh"

  config.vm.define "manager1" do |manager1|
    manager1.vm.box = "centos/7"
    manager1.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "manager2" do |manager2|
    manager2.vm.box = "centos/7"
    manager2.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "manager3" do |manager3|
    manager3.vm.box = "centos/7"
     manager3.vm.network "private_network", type: "dhcp"
  end

end
